torch.nn \
&emsp; 1. Containers - Structure \
&emsp; &emsp; (a) Module - Base class for all neural network modules \
&emsp; &emsp; &emsp; i. init() & forward() - forward defines the computation performed at every call \
&emsp; &emsp; &emsp; ii. All our modules should subclass this one \
&emsp; 2. Convolution Layers \
&emsp; &emsp; (a) Conv1d \
&emsp; &emsp; (b) Conv2d \
&emsp; &emsp; &emsp; i. stride - movement (single number or tuple (sH, sW)) \
&emsp; &emsp; &emsp; ii. weight - kernel \
&emsp; &emsp; &emsp; iii. padding - padding of both sides of input, default as 0 (single number or tuple (padH, padW)) \
&emsp; 3. Pooling Layers \
&emsp; &emsp; (a) MaxPool2d() - Keep important information, but reduce data volume \
&emsp; 4. Non-linear Activations (weighted sum, nonlinearity) \
&emsp; &emsp; (a) ReLU \
&emsp; &emsp; (b) Sigmoid \
&emsp; 5. Normalization Layers - Speed up training (BatchNorm2d()) \
&emsp; 6. Recurrent Layers - LSTM(), RNN() - Text Classification \
&emsp; 7. Transformer Layers - Transformer() \
&emsp; 8. Linear Layers \
&emsp; &emsp; (a) Linear \
&emsp; 9. Dropout Layers - Dropout() (NLP, prevent overfitting) \
&emsp; 10. Sparse Layers

In [10]:
from torch import nn
import torch
import torchvision
from torch.utils.data import DataLoader

c:\Users\Xinxie Wu\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\Xinxie Wu\AppData\Local\Programs\Python\Python310\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(


In [2]:
class MyNetwork(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        y = x + 1
        return y

In [3]:
mynetwork = MyNetwork()
x = torch.tensor(1.0)
output = mynetwork(x)
print(output)

tensor(2.)


Conv2d() example

In [6]:
import torch.nn.functional as F

In [4]:
input = torch.tensor([[1,2,0,3,1],
                      [0,1,2,3,1],
                      [1,2,1,0,0],
                      [5,2,3,1,1],
                      [2,1,0,1,1]])

kernel = torch.tensor([[1,2,1],
                       [0,1,0],
                       [2,1,0]])

In [5]:
input = torch.reshape(input, (1,1,5,5))
kernel = torch.reshape(kernel, (1,1,3,3))

In [7]:
output = F.conv2d(input, kernel, stride=1)
print(output)

tensor([[[[10, 12, 12],
          [18, 16, 16],
          [13,  9,  3]]]])


In [8]:
output = F.conv2d(input, kernel, stride=2)
print(output)

tensor([[[[10, 12],
          [13,  3]]]])


In [9]:
output3 = F.conv2d(input, kernel, stride=1, padding=1)
print(output3)

tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])


MaxPool2d() examples

In [13]:
input = torch.tensor([[1,2,0,3,1],
                      [0,1,2,3,1],
                      [1,2,1,0,0],
                      [5,2,3,1,1],
                      [2,1,0,1,1]], dtype=torch.float32)

kernel = torch.tensor([[1,2,1],
                       [0,1,0],
                       [2,1,0]])

input = torch.reshape(input, (-1,1,5,5))
kernel = torch.reshape(kernel, (1,1,3,3))

In [18]:
class MyNetwork(nn.Module):
    def __init__(self):
        super(MyNetwork, self).__init__()
        self.maxpool1 = nn.MaxPool2d(kernel_size=3,ceil_mode=True)
    
    def forward(self, x):
        y = self.maxpool1(x)
        return y

In [19]:
mynetwork = MyNetwork()
output = mynetwork(input)
print(output)

tensor([[[[2., 3.],
          [5., 1.]]]])


ReLU examples

In [20]:
input = torch.tensor([[1,-0.5],
                      [-1,3]], dtype=torch.float32)

input = torch.reshape(input, (-1,1,2,2))

In [21]:
class MyNetwork(nn.Module):
    def __init__(self):
        super(MyNetwork, self).__init__()
        self.relu1 = nn.ReLU()
    
    def forward(self, x):
        y = self.relu1(x)
        return y

In [22]:
mynetwork = MyNetwork()
output = mynetwork(input)
print(output)

tensor([[[[1., 0.],
          [0., 3.]]]])


Linear examples